// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlYaxgevmCrdr0QEsTmY551md1QjxjM10',
    appId: '1:57974269225:web:afd14315edbd5782940338',
    messagingSenderId: '57974269225',
    projectId: 'smartshift-49870',
    authDomain: 'smartshift-49870.firebaseapp.com',
    storageBucket: 'smartshift-49870.firebasestorage.app',
    measurementId: 'G-7VC088LBES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnKJzpBux9jlk1CG14vCf4dc1uz3ObexQ',
    appId: '1:57974269225:android:042c1ba60f86232b940338',
    messagingSenderId: '57974269225',
    projectId: 'smartshift-49870',
    storageBucket: 'smartshift-49870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Kl9WtgF4BIkXC31du9MXglU2_wa2nVo',
    appId: '1:57974269225:ios:273fb0135c7145ee940338',
    messagingSenderId: '57974269225',
    projectId: 'smartshift-49870',
    storageBucket: 'smartshift-49870.firebasestorage.app',
    iosClientId: '57974269225-veddvq7jt4a5oeufelhp5cqf6cb6nkq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartshiftApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Kl9WtgF4BIkXC31du9MXglU2_wa2nVo',
    appId: '1:57974269225:ios:273fb0135c7145ee940338',
    messagingSenderId: '57974269225',
    projectId: 'smartshift-49870',
    storageBucket: 'smartshift-49870.firebasestorage.app',
    iosClientId: '57974269225-veddvq7jt4a5oeufelhp5cqf6cb6nkq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartshiftApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlYaxgevmCrdr0QEsTmY551md1QjxjM10',
    appId: '1:57974269225:web:8bd92128a0d75cce940338',
    messagingSenderId: '57974269225',
    projectId: 'smartshift-49870',
    authDomain: 'smartshift-49870.firebaseapp.com',
    storageBucket: 'smartshift-49870.firebasestorage.app',
    measurementId: 'G-NW2FRSHKZY',
  );

}